Rappsilber-Laboratory/xiView

js/spectrumViewWrapper.js
network.php

for https://github.com/Rappsilber-Laboratory/xi3-issue-tracker/issues/17

don't show validation buttons unless logged in

---

js/compositeModelType.js

part of fix for https://github.com/Rappsilber-Laboratory/xi3-issue-tracker/issues/47

applyFilter in CompositeModelType updates attribute "ambiguous" of crosslink

---

js/alignModelType.js
js/circularViewBB.js
js/ddMenuViewBB.js

fix annotations in circle, from martin

fix annotations in circle

---

js/networkFrame.js
loadData.php

fixes bug whereby things that should be hidden weren't hidden on start up; extended search meta data (search parameters, etc)

bug fix to hidden; also loads search parameters

---

css/alignViewBB.css
js/NGLViewBB.js
js/distogramViewBB.js
js/matrixViewBB.js
js/networkFrame.js
vendor/c3.js
vendor/ngl_verbose.js

changes from martin - disto svg fix, bigger cross-links in matrix, also updates NGL version

disto svg fix, bigger cross-links in matrix

---

js/downloads.js
loadData.php
vendor/~d3.js

CSV links download crashing if no distances / no pdb file

bug fix; was only downloading CSV links if pdb file loaded

---

js/filterViewBB.js
loadData.php
network.php

removed 6 decimal place rounding from loadData.php to help look at #160,

removed 6 decimal place rounding from loadData.php

---

js/NGLViewBB.js
js/Utils.js
js/distogramViewBB.js
js/linkMetaDataFileChooserBB.js
js/modelUtils.js
js/scatterplotViewBB.js

Fix bug in link metadata import when column names not exactly right

Abstract out some select and option instantiating

---

css/circularViewBB.css
css/distogram.css
css/style.css
js/modelUtils.js
js/scatterplotViewBB.js

nearest link/match in scatterplot tooltip

---

js/networkFrame.js
js/validate.js
network.php

xiSpecConfig.php used to set xiSpec and xiAnnotaotor base URLs

xiSpecConfig.php

---

js/circularViewBB.js
js/distancesObj.js
js/downloads.js

2. Add pdb aligned positions to link download csv

1. Fix circle reordering bug on resizing

---

css/spectrumViewWrapper.css
css/validationPage.css
js/NGLViewBB.js
js/Utils.js
js/circularViewBB.js
js/distogramViewBB.js
js/keyViewBB.js
js/matrixViewBB.js
js/networkFrame.js
js/proteinInfoViewBB.js
js/scatterplotViewBB.js
js/spectrumViewWrapper.js
validate.php

2. Settings view isn't hidden by main spectrum view

1. Better button alignment at top of validation page

---

css/style.css
css/urlSearchBoxViewBB.css
js/NGLViewBB.js
js/Utils.js
js/filterViewBB.js
js/matrixViewBB.js
js/minigramViewBB.js
js/modelUtils.js
js/models.js
js/networkFrame.js
js/urlSearchBoxViewBB.js
network.php

can now share filter state in url

Can now share filter state trhough url query string

---

css/circularViewBB.css
css/filter.css
css/proteinInfoViewBB.css
js/NGLViewBB.js
js/Utils.js
js/alignViewBB3.js
js/circularViewBB.js
js/compositeModelType.js
js/ddMenuViewBB.js
js/filterViewBB.js
js/proteinInfoViewBB.js
js/selectionTableViewBB.js

1. Protein highlighting extended to protein info panel
2. Mouseenter/leave replacing mouseover/out where efficient

Protein highlighting between circle and xinet

---

css/tooltip.css
js/NGLViewBB.js
js/circularViewBB.js
js/modelUtils.js
js/proteinInfoViewBB.js
js/scatterplotViewBB.js

2. Can cancel selections in circle view

1. More logical cross-link tooltips

---

js/NGLViewBB.js
js/compositeModelType.js
js/modelUtils.js

2. Add PDB coverage text to 3D view

1. Toggle link/match selection when CTRL key used

---

js/filterViewBB.js
js/models.js
loadData.php

...now use greater than or equal to

AA apart and pep length filters

---

js/downloads.js
js/selectionTableViewBB.js

added scan index (if available), fragment tolerance, crosslinker mod mass and ion types to CSV match export; 
(updates for renaming calcMZ to matchMZ functions in CLMS-model)

aligning CSV formats

---

css/key.css
js/distogramViewBB.js
js/linkColourAssignment.js
js/minigramViewBB.js
js/networkFrame.js

fix minigram bug when no data loaded;

account for decoy proteins in new colour scheme; 

---

css/key.css
js/compositeModelType.js
js/downloads.js
js/keyViewBB.js

1. 3D Distances stopped exporting after first decoy in link export
2. Matches didn't export link positions for ambiguous matches - NaN instead

Legend changes, bug fix for links / matches export

---

css/style.css
js/PDBFileChooser.js
js/Utils.js
js/alignViewBB3.js
js/distogramViewBB.js
js/scatterplotViewBB.js
js/selectionTableViewBB.js

Not yet found anything to offer the holy grail of searching by multiple sequences...
Also
1. Better d3 select/option updating  …
2. Update selection table on protein name change (proteinMetadataUpdated event)

Can look for pdb code by single protein sequence

---

js/PDBFileChooser.js
js/Utils.js
js/proteinInfoViewBB.js

2. Select Protein for EBI Search dropdown now alphabetically ordered
3. Also same dropdown restricted to selected proteins if any selected

1. Fix bug in protein info view (some crosslinks not shown)

---

css/matrix.css
css/style.css
js/NGLModelWrapperBB.js
js/PDBFileChooser.js
js/modelUtils.js

2. RCSB Uniprot-PDB service now works with selected protein ids only (if selection made)

1. Non-transparent background for matrix

---

css/style.css
js/Utils.js
js/circularViewBB.js
js/keyViewBB.js
js/matrixViewBB.js
js/scatterplotViewBB.js

2. Circle, scatterplot and matrix figure outputs now auto-generate colour scheme keys

1. Fix grey matrix background moving away on zoom

---

css/alignViewBB.css
css/style.css
js/NGLViewBB.js
js/Utils.js
js/alignViewBB3.js
js/circularViewBB.js
js/compositeModelType.js
js/distogramViewBB.js
js/keyViewBB.js
js/linkColourAssignment.js
js/listViewBB.js
js/matrixViewBB.js
js/scatterplotViewBB.js

1. Exported images have search title and info
2. Can now change undefined colour for colour schemes
3. Undefined colour added to exported keys
4. NGL PNG export now includes key

Exported image extras

---

js/NGLModelWrapperBB.js
js/NGLViewBB.js
js/PDBFileChooser.js
js/alignModelType.js
js/linkColourAssignment.js
js/matrixViewBB.js
js/modelUtils.js
tests/tests.js

Along with colour scale to highlight these residues

Can show resiudes in NGL view where only one end of crosslink within PDB

---

css/nglViewBB.css
js/NGLViewBB.js
js/Utils.js
js/matrixViewBB.js
js/networkFrame.js

2. Matrix view filters options to selected proteins if any

1. 3d view reports number of full links shown in view

---

css/matrix.css
css/style.css
js/Utils.js
js/matrixViewBB.js

2. Maximise button added to panels

1. Matrix crosslinks shown as circles

---

js/NGLModelWrapperBB.js
js/NGLUtils.js
js/NGLViewBB.js
js/Utils.js
js/alignModelType.js
js/alignViewBB3.js
js/downloads.js
network.php

2. Haddock and pymol export options in ngl view

1. d3.json rather than d3.text

---

js/compositeModelType.js
js/fdr.js
js/filterModel.js
js/filterViewBB.js
tests/tests.js

2. Remove protein matching pair func from filter - stored in match objects now
3. Added test for search to protein mapping
Signed-off-by: Martin Graham <martinjamesgraham@outlook.com>

1. Remove charge stuff from filter

---

js/goTerm.js
js/goTermsSankeyViewBB.js
js/modelUtils.js
js/networkFrame.js
network.php
tests/tests.js

2. Lazy instantiation of go term property sets (saves about 20MB in memory)

1. Load go file in parallel (saves a couple of seconds)

---

js/filterModel.js
js/goTermsSankeyViewBB.js
js/goTermsViewBB.js
js/networkFrame.js
js/sankey.js
network.php
tests/tests.js

2. Don't update GO view on every render

Load BLOSUM matrices in parallel

---

css/goTermsView.css
js/goTermsSankeyViewBB.js

2. Trying to alleviate text over-crowding

1. Can highlight and select proteins using go term search bar

---

css/tooltip.css
js/NGLModelWrapperBB.js
js/NGLViewBB.js
js/compositeModelType.js
js/distancesObj.js
js/distogramViewBB.js
js/matrixViewBB.js
js/modelUtils.js
js/scatterplotViewBB.js
network.php
tests/tests.js

Distances attached to cross-links meta property when calculated

---

js/NGLModelWrapperBB.js
js/NGLUtils.js
js/PDBFileChooser.js
js/Utils.js
js/compositeModelType.js
js/distogramViewBB.js
js/filterModel.js
js/filterViewBB.js
js/minigramViewBB.js
js/modelUtils.js
js/networkFrame.js
js/urlSearchBoxViewBB.js
tests/tests.js

2. Make initial distance histogram max x value based on max crosslink length

1. Add RCSB PDB auto-loading and output in URL

---

js/NGLModelWrapperBB.js
js/Utils.js
js/compositeModelType.js
js/distogramViewBB.js
js/filterViewBB.js
js/minigramViewBB.js
js/models.js
js/networkFrame.js

2. Better histogram x axis labelling

1. Distance slider included in filter

---

css/filter.css
js/NGLUtils.js
js/NGLViewBB.js
js/Utils.js
js/circleArrange.js
js/circularViewBB.js
js/distogramViewBB.js
js/downloads.js
js/filterModel.js
js/filterViewBB.js
js/linkColourAssignment.js
js/listViewBB.js
js/matrixViewBB.js
js/modelUtils.js
js/models.js
js/networkFrame.js
js/scatterplotViewBB.js
js/searchSummaryViewBB.js
network.php
tests/tests.js

2. Separate minigram model and view generation

1. Add undefined distance filter to distance slider

---

js/Utils.js
js/metaDataFileChoosers.js
js/networkFrame.js
network.php

2. Generalise local storage util routines
3. Only send relevant url query params to spectrumMatches.php

1. Point metadata file loaders to xidocs for csv syntax info.

---

js/filterModel.js
js/filterViewBB.js

Signed-off-by: Martin Graham <martinjamesgraham@outlook.com>

Preprocess runname filter value for efficiency's sake

---

githubForm.html
js/NGLModelWrapperBB.js
js/NGLUtils.js
js/NGLViewBB.js
js/models.js
network.php
tests/qunit.html
tests/tests.js
validate.php

Update JQuery to 3.4.1 and QUnit to 2.9.2 …
Stomp on a couple of 3d view related memory leaks (couple more left)
Fix bug with intermodeldistance flag not lighting up haddock export correctly
Tidying up NGL related code
Rename some variables in ngl-related code for clarity

Library updates and NGL fixes

---

js/NGLModelWrapperBB.js
js/NGLUtils.js
js/NGLViewBB.js

Bit more garbage collecting and some tidier events in 3d code

Fix error where seeting inter-model distances crashed next PDB load
